### ISSUE TITLE
dependencies out of date

### ISSUE THREAD

**Issue by evanwill** [uidaholib/library_assessment#1]
@kandersonko @b-godfrey I don't know anything about this project, but I am getting a bunch of security issue alerts for it. The framework looks out of date.
https://github.com/uidaholib/library_assessment/network/alerts

**Comment by evanwill** [comment]
if this is a historic repository should probably just be set to "archived", if in use should be updated! Thanks

**Comment by b-godfrey** [comment]
Let’s set it to “archived”.  Can you go ahead and do that?

**Comment by evanwill** [comment]
@b-godfrey okay, will do! thanks
